name: Rename Files with Colons
on:
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rename files with colons
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Find files with colons and rename them (replace : with _)
          find . -type f -name '*:*' | while read -r file; do
            newfile=$(echo "$file" | sed 's/:/_/g')
            git mv "$file" "$newfile"
          done
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Rename files with colons to underscores"
            git push origin main
          else
            echo "No files to rename"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
